before_commands:
    - "composer install --prefer-source"

build:
    dependencies:
        before:
            - pecl install ssh-beta

    tests:
        override:
            -
                command: phpunit tests/
                on_node: 1

